global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'product_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['product-service:8050']
        labels:
          application: 'Product Service Application'
  - job_name: 'order_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['order-service:8070']
        labels:
          application: 'Order Service Application'
  - job_name: 'customer_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['customer-service:8090']
        labels:
          application: 'customer Service Application'
  - job_name: 'notification_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['notification-service:8040']
        labels:
          application: 'Notification Service Application'
  - job_name: 'payment_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'payment-service:8060' ]
        labels:
          application: 'payment Service Application'
