eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka
#      defaultZone: http://localhost:8761/eureka
name:
  value: kiran
spring:
  cloud:
    config:
      override-system-properties: false

#management:
#  tracing:
#    sampling:
#      probability: 1.0
