server:
  port: 8090
spring:
  data:
    mongodb:
      username: kiran
      password: kiran123
      host: mongo
      port: 27017
      database: customer
      authentication-database: admin

# Actuator Prometheus Endpoint
management:
  endpoints:
    web:
      exposure:
        include: prometheus