server:
  port: 8040
spring:
  data:
    mongodb:
      username: kiran
      password: kiran123
      host: mongo
      port: 27017
      database: notification
      authentication-database: admin


  kafka:
    consumer:
      bootstrap-servers: ms_kafka:29092
      group-id: paymentGroup,orderGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: orderConfirmation:com.kiran.notification_server.kafka.order.OrderConfirmation,paymentConfirmation:com.kiran.notification_server.kafka.payment.PaymentConfirmation


  mail:
    host: ms-mail-dev
    port: 1025
    username: kiran
    password: kiran123
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000


  # Actuator Prometheus Endpoint
  management:
    endpoints:
      web:
        exposure:
          include: prometheus