server:
  port: 8070
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ms_pg_sql:5432/order
    username: kiran
    password: kiran123
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect


  kafka:
    producer:
      bootstrap-servers: ms_kafka:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: orderConfirmation:com.kiran.order_server.kafka.OrderConfirmation


application:
  config:
    customer-url: http://api-gateway:8222/api/v1/customers
    payment-url: http://api-gateway:8222/api/v1/payments
    product-url: http://api-gateway:8222/api/v1/products


  # Actuator Prometheus Endpoint
  management:
    endpoints:
      web:
        exposure:
          include: prometheus