spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-url: "http://localhost:9098/realms/micro-services"
  config:
    import: optional:configserver:http://config-server:8888
  application:
    name: gateway-service