server:
  port: 8060
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ms_pg_sql:5432/payment
    username: kiran
    password: kiran123
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    producer:
      bootstrap-servers: ms_kafka:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: paymentConfirmation:com.kiran.payment_server.dto.PaymentNotificationRequest
application:
  config:
    product-url: http://api-gateway:8222/api/v1/products


  # Actuator Prometheus Endpoint
  management:
    endpoints:
      web:
        exposure:
          include: prometheus